name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies for php 7.3
      uses: MilesChou/composer-action/7.3/install@master

    - name: Run test suite for php 7.3
      run:  php vendor/bin/phpunit

    - name: Install dependencies for php 7.4
      uses: MilesChou/composer-action/7.4/install@master

    - name: Run test suite for php 7.4
      run: php vendor/bin/phpunit

    - name: Install dependencies for php 8.0
      uses: MilesChou/composer-action/8.0/install@master

    - name: Run test suite for php 8.0
      uses: MilesChou/composer-action/8.0/install@master